### ISSUE TITLE
RHEL & Red Hat confusion

### ISSUE THREAD

**Issue by ad-m** [JeyKeu/font-os#1]
Hi,

I noticed that the Red Hat (company) distro icon is available. However, there is no icon available for Red Hat Enterprise Linux (RHEL; distro provided by RHEL). This is a similar problem to using the name "Microsoft" for the Windows operating system.

What do you think about updating to fix the problem - add RHEL and mark RedHat as deprecated?

Greetings,

**Comment by JunaidQadirB** [comment]
The logo is indeed outdated. 
The Label for the Icon is RedHat and nowhere it is mentioned that it is RHEL.
There seems no icon/logo that representing RHEL, the OS except for the fact that RedHat uses the Redhat logo along with Enterprise Linux text.

If you believe the information above is inaccurate then please share appropriate links to the logo that represents RHEL, I'll update it.

Thanks.

**Comment by ad-m** [comment]
Thank you for explaining your point of view.
